services:
  python-playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BROWSER=chromium
      - HEADLESS=True
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';
    volumes:
      - .:/app
      - ./TestResults:/app/TestResults
    working_dir: /app
    command: >
      pytest -m smoke
